In [9]:
import pip
import pandas as pd
import numpy as np

In [4]:
# Read files

# movieId, title, genres
movies = pd.read_csv('data/movies.csv', sep=',',header=0)

# movieId, imdbId, tmdbId
links = pd.read_csv('data/links.csv', sep=',',header=0)

# userId, movieId, tag, timestamp
tags = pd.read_csv('data/tags.csv', sep=',',header=0)

# userId, movieId, rating, timestamp
ratings = pd.read_csv('data/ratings.txt', sep='\t',header=0)

# tagId, tag
genome_tags = pd.read_csv('data/genome-tags.csv', sep=',',header=0)

# movieId, tagId, relevance
genome_scores = pd.read_csv('data/genome-scores.txt', sep='\t',header=0)

In [63]:
# pd.merge(movies, ratings, on='movieId')

userIds = np.sort(ratings.userId.unique())[:50]
movieIds = np.sort(ratings.movieId.unique())[:20]

userCount = userIds.shape[0]
movieCount = movieIds.shape[0]

In [64]:
matrixA = np.zeros((movieCount, userCount))

for i in range(0, movieCount):
    movieId = movieIds[i]
    for j in range(0, userCount):
        userId = userIds[j]
        rating = ratings[(ratings.userId == userId) & (ratings.movieId == movieId)].rating
        if (rating.any()):
            matrixA[(i, j)] = rating

In [65]:
np.sort(ratings.userId.unique())[:100]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int64)

In [66]:
ratings[(ratings.userId == 2) & (ratings.movieId == 1)].rating

Series([], Name: rating, dtype: float64)

In [147]:
U, s, V = np.linalg.svd(matrixA)

S = np.zeros((movieCount, userCount), dtype=complex)
S[:movieCount, :movieCount] = np.diag(s)
assert(np.allclose(matrixA, np.dot(U, np.dot(S, V))))

U.shape, S.shape, V.shape, s

((20, 20),
 (20, 50),
 (50, 50),
 array([  2.39683000e+01,   1.37066818e+01,   1.34428755e+01,
          1.14009990e+01,   1.00473131e+01,   8.87087563e+00,
          8.44358378e+00,   6.87496314e+00,   5.79799451e+00,
          4.88411757e+00,   4.40318234e+00,   4.00221190e+00,
          3.85010889e+00,   2.61412951e+00,   2.00000000e+00,
          1.91998196e+00,   1.23823554e+00,   3.59379692e-16,
          2.23098602e-16,   1.12762763e-16]))

In [148]:
S_sqrt = np.sqrt(S)
p = np.dot(U, S_sqrt.transpose)
q = np.dot(S_sqrt, V.transpose())

In [113]:
np.hstack((s_sqrt, np.zeros((movieCount, userCount - movieCount)))).shape

(20, 80)

In [126]:
np.allclose(matrixA, np.dot(U, np.dot(s, V)))

True

In [153]:
U, s, V = np.linalg.svd(matrixA, full_matrices=True)
U.shape, V.shape, s.shape

S = np.zeros((movieCount, userCount), dtype=complex)
S[:movieCount, :movieCount] = np.diag(s)
np.allclose(matrixA, np.dot(U, np.dot(S, V)))

True

In [154]:
p[0], q

(array([ -2.95216702e+00+0.j,   9.22820055e-01+0.j,   4.00548878e-01+0.j,
         -1.71660118e+00+0.j,   1.32280558e+00+0.j,  -3.15081449e-01+0.j,
         -6.82127388e-01+0.j,  -2.73260401e-01+0.j,  -4.11754564e-01+0.j,
          1.06618103e-01+0.j,  -1.02146391e-01+0.j,   1.39640605e-01+0.j,
          1.29136424e-01+0.j,   1.30941915e-01+0.j,   1.12890165e-16+0.j,
         -6.54311769e-02+0.j,  -2.74527321e-02+0.j,   2.79932194e-25+0.j,
         -2.52352912e-26+0.j,  -2.25441056e-26+0.j,   0.00000000e+00+0.j,
          0.00000000e+00+0.j,   0.00000000e+00+0.j,   0.00000000e+00+0.j,
          0.00000000e+00+0.j,   0.00000000e+00+0.j,   0.00000000e+00+0.j,
          0.00000000e+00+0.j,   0.00000000e+00+0.j,   0.00000000e+00+0.j,
          0.00000000e+00+0.j,   0.00000000e+00+0.j,   0.00000000e+00+0.j,
          0.00000000e+00+0.j,   0.00000000e+00+0.j,   0.00000000e+00+0.j,
          0.00000000e+00+0.j,   0.00000000e+00+0.j,   0.00000000e+00+0.j,
          0.00000000e+00+0.j,   0.0000